using System.Collections.Generic;

namespace CultureInfoMatcher.Abstract;

internal struct ParadigmLocales {
	internal string locales;
}

internal static partial class Data {
	internal static readonly string[] paradigmLocales = ["en", "en-GB", "es", "es-419", "pt-BR", "pt-PT", "en-Latn-US", "en-Latn-GB", "es-Latn-ES", "es-Latn-419", "pt-Latn-BR", "pt-Latn-PT"];

	internal static readonly Dictionary<string, string[]> matchVariables = new() {
		["$enUS"] = SplitMatchVariables("AS+CA+GU+MH+MP+PH+PR+UM+US+VI"),
		["$cnsar"] = SplitMatchVariables("HK+MO"),
		["$americas"] = SplitMatchVariables("019"),
		["$maghreb"] = SplitMatchVariables("MA+DZ+TN+LY+MR+EH"),
	};

	private static string[] SplitMatchVariables(string plusJoined) =>
		plusJoined.Split('+');

	internal static readonly LanguageMatchInfo[] matches = [
		new(supported: "no", desired: "nb", distance: 1),
		new(supported: "bs", desired: "hr", distance: 4),
		new(supported: "bs", desired: "sh", distance: 4),
		new(supported: "hr", desired: "sh", distance: 4),
		new(supported: "sr", desired: "sh", distance: 4),
		new(supported: "aa", desired: "ssy", distance: 4),
		new(supported: "de", desired: "gsw", distance: 4, oneway: true),
		new(supported: "de", desired: "lb", distance: 4, oneway: true),
		new(supported: "no", desired: "da", distance: 8),
		new(supported: "nb", desired: "da", distance: 8),
		new(supported: "ru", desired: "ab", distance: 30, oneway: true),
		new(supported: "en", desired: "ach", distance: 30, oneway: true),
		new(supported: "nl", desired: "af", distance: 20, oneway: true),
		new(supported: "en", desired: "ak", distance: 30, oneway: true),
		new(supported: "en", desired: "am", distance: 30, oneway: true),
		new(supported: "es", desired: "ay", distance: 20, oneway: true),
		new(supported: "ru", desired: "az", distance: 30, oneway: true),
		new(supported: "ur", desired: "bal", distance: 20, oneway: true),
		new(supported: "ru", desired: "be", distance: 20, oneway: true),
		new(supported: "en", desired: "bem", distance: 30, oneway: true),
		new(supported: "hi", desired: "bh", distance: 30, oneway: true),
		new(supported: "en", desired: "bn", distance: 30, oneway: true),
		new(supported: "zh", desired: "bo", distance: 20, oneway: true),
		new(supported: "fr", desired: "br", distance: 20, oneway: true),
		new(supported: "es", desired: "ca", distance: 20, oneway: true),
		new(supported: "fil", desired: "ceb", distance: 30, oneway: true),
		new(supported: "en", desired: "chr", distance: 20, oneway: true),
		new(supported: "ar", desired: "ckb", distance: 30, oneway: true),
		new(supported: "fr", desired: "co", distance: 20, oneway: true),
		new(supported: "fr", desired: "crs", distance: 20, oneway: true),
		new(supported: "sk", desired: "cs", distance: 20),
		new(supported: "en", desired: "cy", distance: 20, oneway: true),
		new(supported: "en", desired: "ee", distance: 30, oneway: true),
		new(supported: "en", desired: "eo", distance: 30, oneway: true),
		new(supported: "es", desired: "eu", distance: 20, oneway: true),
		new(supported: "da", desired: "fo", distance: 20, oneway: true),
		new(supported: "nl", desired: "fy", distance: 20, oneway: true),
		new(supported: "en", desired: "ga", distance: 20, oneway: true),
		new(supported: "en", desired: "gaa", distance: 30, oneway: true),
		new(supported: "en", desired: "gd", distance: 20, oneway: true),
		new(supported: "es", desired: "gl", distance: 20, oneway: true),
		new(supported: "es", desired: "gn", distance: 20, oneway: true),
		new(supported: "hi", desired: "gu", distance: 30, oneway: true),
		new(supported: "en", desired: "ha", distance: 30, oneway: true),
		new(supported: "en", desired: "haw", distance: 20, oneway: true),
		new(supported: "fr", desired: "ht", distance: 20, oneway: true),
		new(supported: "ru", desired: "hy", distance: 30, oneway: true),
		new(supported: "en", desired: "ia", distance: 30, oneway: true),
		new(supported: "en", desired: "ig", distance: 30, oneway: true),
		new(supported: "en", desired: "is", distance: 20, oneway: true),
		new(supported: "id", desired: "jv", distance: 20, oneway: true),
		new(supported: "en", desired: "ka", distance: 30, oneway: true),
		new(supported: "fr", desired: "kg", distance: 30, oneway: true),
		new(supported: "ru", desired: "kk", distance: 30, oneway: true),
		new(supported: "en", desired: "km", distance: 30, oneway: true),
		new(supported: "en", desired: "kn", distance: 30, oneway: true),
		new(supported: "en", desired: "kri", distance: 30, oneway: true),
		new(supported: "tr", desired: "ku", distance: 30, oneway: true),
		new(supported: "ru", desired: "ky", distance: 30, oneway: true),
		new(supported: "it", desired: "la", distance: 20, oneway: true),
		new(supported: "en", desired: "lg", distance: 30, oneway: true),
		new(supported: "fr", desired: "ln", distance: 30, oneway: true),
		new(supported: "en", desired: "lo", distance: 30, oneway: true),
		new(supported: "en", desired: "loz", distance: 30, oneway: true),
		new(supported: "fr", desired: "lua", distance: 30, oneway: true),
		new(supported: "hi", desired: "mai", distance: 20, oneway: true),
		new(supported: "en", desired: "mfe", distance: 30, oneway: true),
		new(supported: "fr", desired: "mg", distance: 30, oneway: true),
		new(supported: "en", desired: "mi", distance: 20, oneway: true),
		new(supported: "en", desired: "ml", distance: 30, oneway: true),
		new(supported: "ru", desired: "mn", distance: 30, oneway: true),
		new(supported: "hi", desired: "mr", distance: 30, oneway: true),
		new(supported: "id", desired: "ms", distance: 30, oneway: true),
		new(supported: "en", desired: "mt", distance: 30, oneway: true),
		new(supported: "en", desired: "my", distance: 30, oneway: true),
		new(supported: "en", desired: "ne", distance: 30, oneway: true),
		new(supported: "nb", desired: "nn", distance: 20),
		new(supported: "no", desired: "nn", distance: 20),
		new(supported: "en", desired: "nso", distance: 30, oneway: true),
		new(supported: "en", desired: "ny", distance: 30, oneway: true),
		new(supported: "en", desired: "nyn", distance: 30, oneway: true),
		new(supported: "fr", desired: "oc", distance: 20, oneway: true),
		new(supported: "en", desired: "om", distance: 30, oneway: true),
		new(supported: "en", desired: "or", distance: 30, oneway: true),
		new(supported: "en", desired: "pa", distance: 30, oneway: true),
		new(supported: "en", desired: "pcm", distance: 20, oneway: true),
		new(supported: "en", desired: "ps", distance: 30, oneway: true),
		new(supported: "es", desired: "qu", distance: 30, oneway: true),
		new(supported: "de", desired: "rm", distance: 20, oneway: true),
		new(supported: "en", desired: "rn", distance: 30, oneway: true),
		new(supported: "fr", desired: "rw", distance: 30, oneway: true),
		new(supported: "hi", desired: "sa", distance: 30, oneway: true),
		new(supported: "en", desired: "sd", distance: 30, oneway: true),
		new(supported: "en", desired: "si", distance: 30, oneway: true),
		new(supported: "en", desired: "sn", distance: 30, oneway: true),
		new(supported: "en", desired: "so", distance: 30, oneway: true),
		new(supported: "en", desired: "sq", distance: 30, oneway: true),
		new(supported: "en", desired: "st", distance: 30, oneway: true),
		new(supported: "id", desired: "su", distance: 20, oneway: true),
		new(supported: "en", desired: "sw", distance: 30, oneway: true),
		new(supported: "en", desired: "ta", distance: 30, oneway: true),
		new(supported: "en", desired: "te", distance: 30, oneway: true),
		new(supported: "ru", desired: "tg", distance: 30, oneway: true),
		new(supported: "en", desired: "ti", distance: 30, oneway: true),
		new(supported: "ru", desired: "tk", distance: 30, oneway: true),
		new(supported: "en", desired: "tlh", distance: 30, oneway: true),
		new(supported: "en", desired: "tn", distance: 30, oneway: true),
		new(supported: "en", desired: "to", distance: 30, oneway: true),
		new(supported: "ru", desired: "tt", distance: 30, oneway: true),
		new(supported: "en", desired: "tum", distance: 30, oneway: true),
		new(supported: "zh", desired: "ug", distance: 20, oneway: true),
		new(supported: "ru", desired: "uk", distance: 20, oneway: true),
		new(supported: "en", desired: "ur", distance: 30, oneway: true),
		new(supported: "ru", desired: "uz", distance: 30, oneway: true),
		new(supported: "fr", desired: "wo", distance: 30, oneway: true),
		new(supported: "en", desired: "xh", distance: 30, oneway: true),
		new(supported: "en", desired: "yi", distance: 30, oneway: true),
		new(supported: "en", desired: "yo", distance: 30, oneway: true),
		new(supported: "zh", desired: "za", distance: 20, oneway: true),
		new(supported: "en", desired: "zu", distance: 30, oneway: true),
		new(supported: "ar", desired: "aao", distance: 10, oneway: true),
		new(supported: "ar", desired: "abh", distance: 10, oneway: true),
		new(supported: "ar", desired: "abv", distance: 10, oneway: true),
		new(supported: "ar", desired: "acm", distance: 10, oneway: true),
		new(supported: "ar", desired: "acq", distance: 10, oneway: true),
		new(supported: "ar", desired: "acw", distance: 10, oneway: true),
		new(supported: "ar", desired: "acx", distance: 10, oneway: true),
		new(supported: "ar", desired: "acy", distance: 10, oneway: true),
		new(supported: "ar", desired: "adf", distance: 10, oneway: true),
		new(supported: "ar", desired: "aeb", distance: 10, oneway: true),
		new(supported: "ar", desired: "aec", distance: 10, oneway: true),
		new(supported: "ar", desired: "afb", distance: 10, oneway: true),
		new(supported: "ar", desired: "ajp", distance: 10, oneway: true),
		new(supported: "ar", desired: "apc", distance: 10, oneway: true),
		new(supported: "ar", desired: "apd", distance: 10, oneway: true),
		new(supported: "ar", desired: "arq", distance: 10, oneway: true),
		new(supported: "ar", desired: "ars", distance: 10, oneway: true),
		new(supported: "ar", desired: "ary", distance: 10, oneway: true),
		new(supported: "ar", desired: "arz", distance: 10, oneway: true),
		new(supported: "ar", desired: "auz", distance: 10, oneway: true),
		new(supported: "ar", desired: "avl", distance: 10, oneway: true),
		new(supported: "ar", desired: "ayh", distance: 10, oneway: true),
		new(supported: "ar", desired: "ayl", distance: 10, oneway: true),
		new(supported: "ar", desired: "ayn", distance: 10, oneway: true),
		new(supported: "ar", desired: "ayp", distance: 10, oneway: true),
		new(supported: "ar", desired: "bbz", distance: 10, oneway: true),
		new(supported: "ar", desired: "pga", distance: 10, oneway: true),
		new(supported: "ar", desired: "shu", distance: 10, oneway: true),
		new(supported: "ar", desired: "ssh", distance: 10, oneway: true),
		new(supported: "az", desired: "azb", distance: 10, oneway: true),
		new(supported: "et", desired: "vro", distance: 10, oneway: true),
		new(supported: "ff", desired: "ffm", distance: 10, oneway: true),
		new(supported: "ff", desired: "fub", distance: 10, oneway: true),
		new(supported: "ff", desired: "fue", distance: 10, oneway: true),
		new(supported: "ff", desired: "fuf", distance: 10, oneway: true),
		new(supported: "ff", desired: "fuh", distance: 10, oneway: true),
		new(supported: "ff", desired: "fui", distance: 10, oneway: true),
		new(supported: "ff", desired: "fuq", distance: 10, oneway: true),
		new(supported: "ff", desired: "fuv", distance: 10, oneway: true),
		new(supported: "gn", desired: "gnw", distance: 10, oneway: true),
		new(supported: "gn", desired: "gui", distance: 10, oneway: true),
		new(supported: "gn", desired: "gun", distance: 10, oneway: true),
		new(supported: "gn", desired: "nhd", distance: 10, oneway: true),
		new(supported: "iu", desired: "ikt", distance: 10, oneway: true),
		new(supported: "kln", desired: "enb", distance: 10, oneway: true),
		new(supported: "kln", desired: "eyo", distance: 10, oneway: true),
		new(supported: "kln", desired: "niq", distance: 10, oneway: true),
		new(supported: "kln", desired: "oki", distance: 10, oneway: true),
		new(supported: "kln", desired: "pko", distance: 10, oneway: true),
		new(supported: "kln", desired: "sgc", distance: 10, oneway: true),
		new(supported: "kln", desired: "tec", distance: 10, oneway: true),
		new(supported: "kln", desired: "tuy", distance: 10, oneway: true),
		new(supported: "kok", desired: "gom", distance: 10, oneway: true),
		new(supported: "kpe", desired: "gkp", distance: 10, oneway: true),
		new(supported: "luy", desired: "ida", distance: 10, oneway: true),
		new(supported: "luy", desired: "lkb", distance: 10, oneway: true),
		new(supported: "luy", desired: "lko", distance: 10, oneway: true),
		new(supported: "luy", desired: "lks", distance: 10, oneway: true),
		new(supported: "luy", desired: "lri", distance: 10, oneway: true),
		new(supported: "luy", desired: "lrm", distance: 10, oneway: true),
		new(supported: "luy", desired: "lsm", distance: 10, oneway: true),
		new(supported: "luy", desired: "lto", distance: 10, oneway: true),
		new(supported: "luy", desired: "lts", distance: 10, oneway: true),
		new(supported: "luy", desired: "lwg", distance: 10, oneway: true),
		new(supported: "luy", desired: "nle", distance: 10, oneway: true),
		new(supported: "luy", desired: "nyd", distance: 10, oneway: true),
		new(supported: "luy", desired: "rag", distance: 10, oneway: true),
		new(supported: "lv", desired: "ltg", distance: 10, oneway: true),
		new(supported: "mg", desired: "bhr", distance: 10, oneway: true),
		new(supported: "mg", desired: "bjq", distance: 10, oneway: true),
		new(supported: "mg", desired: "bmm", distance: 10, oneway: true),
		new(supported: "mg", desired: "bzc", distance: 10, oneway: true),
		new(supported: "mg", desired: "msh", distance: 10, oneway: true),
		new(supported: "mg", desired: "skg", distance: 10, oneway: true),
		new(supported: "mg", desired: "tdx", distance: 10, oneway: true),
		new(supported: "mg", desired: "tkg", distance: 10, oneway: true),
		new(supported: "mg", desired: "txy", distance: 10, oneway: true),
		new(supported: "mg", desired: "xmv", distance: 10, oneway: true),
		new(supported: "mg", desired: "xmw", distance: 10, oneway: true),
		new(supported: "mn", desired: "mvf", distance: 10, oneway: true),
		new(supported: "ms", desired: "bjn", distance: 10, oneway: true),
		new(supported: "ms", desired: "btj", distance: 10, oneway: true),
		new(supported: "ms", desired: "bve", distance: 10, oneway: true),
		new(supported: "ms", desired: "bvu", distance: 10, oneway: true),
		new(supported: "ms", desired: "coa", distance: 10, oneway: true),
		new(supported: "ms", desired: "dup", distance: 10, oneway: true),
		new(supported: "ms", desired: "hji", distance: 10, oneway: true),
		new(supported: "ms", desired: "id", distance: 10, oneway: true),
		new(supported: "ms", desired: "jak", distance: 10, oneway: true),
		new(supported: "ms", desired: "jax", distance: 10, oneway: true),
		new(supported: "ms", desired: "kvb", distance: 10, oneway: true),
		new(supported: "ms", desired: "kvr", distance: 10, oneway: true),
		new(supported: "ms", desired: "kxd", distance: 10, oneway: true),
		new(supported: "ms", desired: "lce", distance: 10, oneway: true),
		new(supported: "ms", desired: "lcf", distance: 10, oneway: true),
		new(supported: "ms", desired: "liw", distance: 10, oneway: true),
		new(supported: "ms", desired: "max", distance: 10, oneway: true),
		new(supported: "ms", desired: "meo", distance: 10, oneway: true),
		new(supported: "ms", desired: "mfa", distance: 10, oneway: true),
		new(supported: "ms", desired: "mfb", distance: 10, oneway: true),
		new(supported: "ms", desired: "min", distance: 10, oneway: true),
		new(supported: "ms", desired: "mqg", distance: 10, oneway: true),
		new(supported: "ms", desired: "msi", distance: 10, oneway: true),
		new(supported: "ms", desired: "mui", distance: 10, oneway: true),
		new(supported: "ms", desired: "orn", distance: 10, oneway: true),
		new(supported: "ms", desired: "ors", distance: 10, oneway: true),
		new(supported: "ms", desired: "pel", distance: 10, oneway: true),
		new(supported: "ms", desired: "pse", distance: 10, oneway: true),
		new(supported: "ms", desired: "tmw", distance: 10, oneway: true),
		new(supported: "ms", desired: "urk", distance: 10, oneway: true),
		new(supported: "ms", desired: "vkk", distance: 10, oneway: true),
		new(supported: "ms", desired: "vkt", distance: 10, oneway: true),
		new(supported: "ms", desired: "xmm", distance: 10, oneway: true),
		new(supported: "ms", desired: "zlm", distance: 10, oneway: true),
		new(supported: "ms", desired: "zmi", distance: 10, oneway: true),
		new(supported: "ne", desired: "dty", distance: 10, oneway: true),
		new(supported: "om", desired: "gax", distance: 10, oneway: true),
		new(supported: "om", desired: "hae", distance: 10, oneway: true),
		new(supported: "om", desired: "orc", distance: 10, oneway: true),
		new(supported: "or", desired: "spv", distance: 10, oneway: true),
		new(supported: "ps", desired: "pbt", distance: 10, oneway: true),
		new(supported: "ps", desired: "pst", distance: 10, oneway: true),
		new(supported: "qu", desired: "qub", distance: 10, oneway: true),
		new(supported: "qu", desired: "qud", distance: 10, oneway: true),
		new(supported: "qu", desired: "quf", distance: 10, oneway: true),
		new(supported: "qu", desired: "qug", distance: 10, oneway: true),
		new(supported: "qu", desired: "quh", distance: 10, oneway: true),
		new(supported: "qu", desired: "quk", distance: 10, oneway: true),
		new(supported: "qu", desired: "qul", distance: 10, oneway: true),
		new(supported: "qu", desired: "qup", distance: 10, oneway: true),
		new(supported: "qu", desired: "qur", distance: 10, oneway: true),
		new(supported: "qu", desired: "qus", distance: 10, oneway: true),
		new(supported: "qu", desired: "quw", distance: 10, oneway: true),
		new(supported: "qu", desired: "qux", distance: 10, oneway: true),
		new(supported: "qu", desired: "quy", distance: 10, oneway: true),
		new(supported: "qu", desired: "qva", distance: 10, oneway: true),
		new(supported: "qu", desired: "qvc", distance: 10, oneway: true),
		new(supported: "qu", desired: "qve", distance: 10, oneway: true),
		new(supported: "qu", desired: "qvh", distance: 10, oneway: true),
		new(supported: "qu", desired: "qvi", distance: 10, oneway: true),
		new(supported: "qu", desired: "qvj", distance: 10, oneway: true),
		new(supported: "qu", desired: "qvl", distance: 10, oneway: true),
		new(supported: "qu", desired: "qvm", distance: 10, oneway: true),
		new(supported: "qu", desired: "qvn", distance: 10, oneway: true),
		new(supported: "qu", desired: "qvo", distance: 10, oneway: true),
		new(supported: "qu", desired: "qvp", distance: 10, oneway: true),
		new(supported: "qu", desired: "qvs", distance: 10, oneway: true),
		new(supported: "qu", desired: "qvw", distance: 10, oneway: true),
		new(supported: "qu", desired: "qvz", distance: 10, oneway: true),
		new(supported: "qu", desired: "qwa", distance: 10, oneway: true),
		new(supported: "qu", desired: "qwc", distance: 10, oneway: true),
		new(supported: "qu", desired: "qwh", distance: 10, oneway: true),
		new(supported: "qu", desired: "qws", distance: 10, oneway: true),
		new(supported: "qu", desired: "qxa", distance: 10, oneway: true),
		new(supported: "qu", desired: "qxc", distance: 10, oneway: true),
		new(supported: "qu", desired: "qxh", distance: 10, oneway: true),
		new(supported: "qu", desired: "qxl", distance: 10, oneway: true),
		new(supported: "qu", desired: "qxn", distance: 10, oneway: true),
		new(supported: "qu", desired: "qxo", distance: 10, oneway: true),
		new(supported: "qu", desired: "qxp", distance: 10, oneway: true),
		new(supported: "qu", desired: "qxr", distance: 10, oneway: true),
		new(supported: "qu", desired: "qxt", distance: 10, oneway: true),
		new(supported: "qu", desired: "qxu", distance: 10, oneway: true),
		new(supported: "qu", desired: "qxw", distance: 10, oneway: true),
		new(supported: "sc", desired: "sdc", distance: 10, oneway: true),
		new(supported: "sc", desired: "sdn", distance: 10, oneway: true),
		new(supported: "sc", desired: "sro", distance: 10, oneway: true),
		new(supported: "sq", desired: "aae", distance: 10, oneway: true),
		new(supported: "sq", desired: "aat", distance: 10, oneway: true),
		new(supported: "sq", desired: "aln", distance: 10, oneway: true),
		new(supported: "syr", desired: "aii", distance: 10, oneway: true),
		new(supported: "uz", desired: "uzs", distance: 10, oneway: true),
		new(supported: "yi", desired: "yih", distance: 10, oneway: true),
		new(supported: "zh", desired: "cdo", distance: 10, oneway: true),
		new(supported: "zh", desired: "cjy", distance: 10, oneway: true),
		new(supported: "zh", desired: "cpx", distance: 10, oneway: true),
		new(supported: "zh", desired: "czh", distance: 10, oneway: true),
		new(supported: "zh", desired: "czo", distance: 10, oneway: true),
		new(supported: "zh", desired: "gan", distance: 10, oneway: true),
		new(supported: "zh", desired: "hak", distance: 10, oneway: true),
		new(supported: "zh", desired: "hsn", distance: 10, oneway: true),
		new(supported: "zh", desired: "lzh", distance: 10, oneway: true),
		new(supported: "zh", desired: "mnp", distance: 10, oneway: true),
		new(supported: "zh", desired: "nan", distance: 10, oneway: true),
		new(supported: "zh", desired: "wuu", distance: 10, oneway: true),
		new(supported: "zh", desired: "yue", distance: 10, oneway: true),
		new(supported: "*", desired: "*", distance: 80),
		new(supported: "en-Latn", desired: "am-Ethi", distance: 10, oneway: true),
		new(supported: "ru-Cyrl", desired: "az-Latn", distance: 10, oneway: true),
		new(supported: "en-Latn", desired: "bn-Beng", distance: 10, oneway: true),
		new(supported: "zh-Hans", desired: "bo-Tibt", distance: 10, oneway: true),
		new(supported: "ru-Cyrl", desired: "hy-Armn", distance: 10, oneway: true),
		new(supported: "en-Latn", desired: "ka-Geor", distance: 10, oneway: true),
		new(supported: "en-Latn", desired: "km-Khmr", distance: 10, oneway: true),
		new(supported: "en-Latn", desired: "kn-Knda", distance: 10, oneway: true),
		new(supported: "en-Latn", desired: "lo-Laoo", distance: 10, oneway: true),
		new(supported: "en-Latn", desired: "ml-Mlym", distance: 10, oneway: true),
		new(supported: "en-Latn", desired: "my-Mymr", distance: 10, oneway: true),
		new(supported: "en-Latn", desired: "ne-Deva", distance: 10, oneway: true),
		new(supported: "en-Latn", desired: "or-Orya", distance: 10, oneway: true),
		new(supported: "en-Latn", desired: "pa-Guru", distance: 10, oneway: true),
		new(supported: "en-Latn", desired: "ps-Arab", distance: 10, oneway: true),
		new(supported: "en-Latn", desired: "sd-Arab", distance: 10, oneway: true),
		new(supported: "en-Latn", desired: "si-Sinh", distance: 10, oneway: true),
		new(supported: "en-Latn", desired: "ta-Taml", distance: 10, oneway: true),
		new(supported: "en-Latn", desired: "te-Telu", distance: 10, oneway: true),
		new(supported: "en-Latn", desired: "ti-Ethi", distance: 10, oneway: true),
		new(supported: "ru-Cyrl", desired: "tk-Latn", distance: 10, oneway: true),
		new(supported: "en-Latn", desired: "ur-Arab", distance: 10, oneway: true),
		new(supported: "ru-Cyrl", desired: "uz-Latn", distance: 10, oneway: true),
		new(supported: "en-Latn", desired: "yi-Hebr", distance: 10, oneway: true),
		new(supported: "sr-Cyrl", desired: "sr-Latn", distance: 5),
		new(supported: "zh-Hans", desired: "za-Latn", distance: 10, oneway: true),
		new(supported: "zh-Hans", desired: "zh-Hani", distance: 20, oneway: true),
		new(supported: "zh-Hant", desired: "zh-Hani", distance: 20, oneway: true),
		new(supported: "ar-Arab", desired: "ar-Latn", distance: 20, oneway: true),
		new(supported: "bn-Beng", desired: "bn-Latn", distance: 20, oneway: true),
		new(supported: "gu-Gujr", desired: "gu-Latn", distance: 20, oneway: true),
		new(supported: "hi-Deva", desired: "hi-Latn", distance: 20, oneway: true),
		new(supported: "kn-Knda", desired: "kn-Latn", distance: 20, oneway: true),
		new(supported: "ml-Mlym", desired: "ml-Latn", distance: 20, oneway: true),
		new(supported: "mr-Deva", desired: "mr-Latn", distance: 20, oneway: true),
		new(supported: "ta-Taml", desired: "ta-Latn", distance: 20, oneway: true),
		new(supported: "te-Telu", desired: "te-Latn", distance: 20, oneway: true),
		new(supported: "zh-Hans", desired: "zh-Latn", distance: 20, oneway: true),
		new(supported: "ja-Jpan", desired: "ja-Latn", distance: 5, oneway: true),
		new(supported: "ja-Jpan", desired: "ja-Hani", distance: 5, oneway: true),
		new(supported: "ja-Jpan", desired: "ja-Hira", distance: 5, oneway: true),
		new(supported: "ja-Jpan", desired: "ja-Kana", distance: 5, oneway: true),
		new(supported: "ja-Jpan", desired: "ja-Hrkt", distance: 5, oneway: true),
		new(supported: "ja-Hrkt", desired: "ja-Hira", distance: 5, oneway: true),
		new(supported: "ja-Hrkt", desired: "ja-Kana", distance: 5, oneway: true),
		new(supported: "ko-Kore", desired: "ko-Hani", distance: 5, oneway: true),
		new(supported: "ko-Kore", desired: "ko-Hang", distance: 5, oneway: true),
		new(supported: "ko-Kore", desired: "ko-Jamo", distance: 5, oneway: true),
		new(supported: "ko-Hang", desired: "ko-Jamo", distance: 5, oneway: true),
		new(supported: "*-*", desired: "*-*", distance: 50),
		new(supported: "ar-*-$maghreb", desired: "ar-*-$maghreb", distance: 4),
		new(supported: "ar-*-$!maghreb", desired: "ar-*-$!maghreb", distance: 4),
		new(supported: "ar-*-*", desired: "ar-*-*", distance: 5),
		new(supported: "en-*-$enUS", desired: "en-*-$enUS", distance: 4),
		new(supported: "en-*-GB", desired: "en-*-$!enUS", distance: 3),
		new(supported: "en-*-$!enUS", desired: "en-*-$!enUS", distance: 4),
		new(supported: "en-*-*", desired: "en-*-*", distance: 5),
		new(supported: "es-*-$americas", desired: "es-*-$americas", distance: 4),
		new(supported: "es-*-$!americas", desired: "es-*-$!americas", distance: 4),
		new(supported: "es-*-*", desired: "es-*-*", distance: 5),
		new(supported: "pt-*-$americas", desired: "pt-*-$americas", distance: 4),
		new(supported: "pt-*-$!americas", desired: "pt-*-$!americas", distance: 4),
		new(supported: "pt-*-*", desired: "pt-*-*", distance: 5),
		new(supported: "zh-Hant-$cnsar", desired: "zh-Hant-$cnsar", distance: 4),
		new(supported: "zh-Hant-$!cnsar", desired: "zh-Hant-$!cnsar", distance: 4),
		new(supported: "zh-Hant-*", desired: "zh-Hant-*", distance: 5),
		new(supported: "*-*-*", desired: "*-*-*", distance: 4),
	];
}
